apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
spec:
  selector:
    matchLabels:
      app: webserver
  replicas: 1
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - name: webserver
        image: registry:5000/webserver:latest
        resources:
          limits:
            cpu: 300m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          exec:
            command:
              - nginx 
              - -V
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 1
        readinessProbe:
          exec:
            command:
              - nginx
              - -h
          initialDelaySeconds: 20
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 1
        volumeMounts:
          - mountPath: "/etc/nginx/data"
            name: pv-storage
      securityContext:
        fsGroup: 1001
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: pv-claim