apiVersion: v1
kind: Service
metadata:
  # This name uniquely identifies the service
  name: minio
spec:
  type: ClusterIP
  ports:
    - port: 9000
      name: inside
      targetPort: 9000
      protocol: TCP
    - port: 9001
      name: webui
      targetPort: 9001
      protocol: TCP
  selector:
    # Looks for labels `app:minio` in the namespace and applies the spec
    app: minio